kind: pipeline
type: docker
name: lesson3

steps:
- name: Build
  image: plugins/docker
  settings:
    repo: mdsn/drone-ci-demo
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password