dist: xenial

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t $DOCKER_USERNAME/travis-ci-build-stages-demo:0.0.1 .
      - docker push $DOCKER_USERNAME/travis-ci-build-stages-demo:0.0.1